### ISSUE TITLE
java.lang.NoClassDefFoundError: aavax.xml.stream.FactoryFinder

### ISSUE THREAD

**Issue by rashiq-tech** [andruhon/android5xlsx#19]
Its my first time implementing apache POI library.
I cant figure why this error occurs while reading from xlsx file.
I do the exact same methods and file used to read. But still this error occurs.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oxcion.trueaccount, PID: 11153
    java.lang.NoClassDefFoundError: aavax.xml.stream.FactoryFinder
        at a.a.b.b.a(:36)
        at a.a.b.b.a(:42)
        at a.a.b.b.a(:91)
        at a.a.b.c.a(:30)
        at e.a.a.i.b.p.j.b.<clinit>(:41)
        at e.a.a.i.b.a.r(:162)
        at e.a.a.i.b.a.<init>(:142)
        at e.a.a.i.b.b.<init>(:37)
        at e.a.a.i.b.n.<init>(:87)
        at e.a.a.i.b.a.a(:273)
        at e.a.a.k.g.a(:37)
        at e.a.a.l.c.b0.<init>(:266)
        at com.oxcion.trueaccount.controller.ImportExportActivity.o(:44)
        at com.oxcion.trueaccount.controller.ImportExportActivity.a(:36)
        at d.d.a.b.x.onClick(lambda)
        at android.view.View.performClick(View.java:4791)
        at android.view.View$PerformClick.run(View.java:19884)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by ShahoodulHassan** [comment]
In my case, it is appearing on Samsung devices.
Anyone knows how to resolve this?
