### ISSUE TITLE
Not an issue, just a THANKS

### ISSUE THREAD

**Issue by devnull69** [andruhon/android5xlsx#5]
Hi there,

you may (of course) close this "issue" because it is just a THANK YOU

Your two manipulated JARs saved my day ... actually it saved almost three days of me struggling :-)

Greetings!
Thomas

**Comment by devnull69** [comment]
I was happy ... until now :-)

Unfortunately the evaluation of cell formulas doesn't work with your JARs on Android. The same cells can be evaluated just fine using POI in a Java application.

Do you happen to have a solution for this, maybe?

My code:

```
            FormulaEvaluator evaluator = wb.getCreationHelper().createFormulaEvaluator();
            CellValue cv = evaluator.evaluate(cell);
            result = cv.getNumberValue();

```

Line #2 just fails silently ... no errors anywhere (not even logcat)

**Comment by devnull69** [comment]
Ok I see an Exception

```
java.lang.ExceptionInInitializerError
                                                                        at org.apache.poi.ss.formula.eval.FunctionEval.produceFunctions(FunctionEval.java:91)
                                                                        at org.apache.poi.ss.formula.eval.FunctionEval.<clinit>(FunctionEval.java:55)
                                                                        at org.apache.poi.ss.formula.OperationEvaluatorFactory.evaluate(OperationEvaluatorFactory.java:132)
                                                                        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:503)
                                                                        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:263)
                                                                        at org.apache.poi.ss.formula.WorkbookEvaluator.evaluate(WorkbookEvaluator.java:205)
                                                                        at org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator.evaluateFormulaCellValue(XSSFFormulaEvaluator.java:267)
                                                                        at org.apache.poi.xssf.usermodel.XSSFFormulaEvaluator.evaluate(XSSFFormulaEvaluator.java:120)
                                                                        at org.theiner.haushalt.util.ExcelHelper.getCellValue(ExcelHelper.java:24)
                                                                        at org.theiner.haushalt.util.HTTPHelper.getHaushaltsplanData(HTTPHelper.java:89)
                                                                        at org.theiner.haushalt.async.GetHaushaltsplanDataTask.doInBackground(GetHaushaltsplanDataTask.java:26)
                                                                        at org.theiner.haushalt.async.GetHaushaltsplanDataTask.doInBackground(GetHaushaltsplanDataTask.java:12)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
                                                                     Caused by: java.util.regex.PatternSyntaxException: U_ILLEGAL_ARGUMENT_ERROR
                                                                    \P{IsL}
                                                                        at java.util.regex.Pattern.compileImpl(Native Method)
                                                                        at java.util.regex.Pattern.compile(Pattern.java:411)
                                                                        at java.util.regex.Pattern.<init>(Pattern.java:394)
                                                                        at java.util.regex.Pattern.compile(Pattern.java:381)
                                                                        at org.apache.poi.ss.formula.functions.TextFunction$5.<init>(TextFunction.java:124)
                                                                        at org.apache.poi.ss.formula.functions.TextFunction.<clinit>(TextFunction.java:123)

```

It is coming from FunctionEval.java

`retval[114] = TextFunction.PROPER;
`

and TextFunction.java has this

`final Pattern nonAlphabeticPattern = Pattern.compile("\\P{IsL}");
`

It seems like java.util.regex cannot handle this pattern on Android ...

**Comment by devnull69** [comment]
I recompiled the poi 3.12 sources with a small change

`final Pattern nonAlphabeticPattern = Pattern.compile("\\P{L}");`

Then I replaced the resulting class files in your JAR. It worked!

If you want I could fork the project and send you a pull request afterwards.

**Comment by andruhon** [comment]
Hi @devnull69, yes please. 
I'll put your stackoverflow discussion here, for reference
http://stackoverflow.com/questions/38376190/patternsyntaxexception-using-apache-poi

**Comment by centic9** [comment]
In POI trunk we now have rewritten the PROPER function to not use regular expressions at all and also fixed a few cases where the method did behave incorrectly, e.g. on some accented characters, see https://github.com/apache/poi/commit/aec95a44918e5331f0d3a746202c713bc8ac6aad

**Comment by andruhon** [comment]
Thanks @centic9 ! Is there a plan date for the next release including this fix?

**Comment by centic9** [comment]
Unfortunately no fixed plan as we release whenever we have enough new/fixed stuff. But beta3 or final should be available in the next few weeks.

**Comment by devnull69** [comment]
Did you notice my pull request?

**Comment by andruhon** [comment]
@devnull69 I did. Wery busy at work now. Can't just merge, need to check what's inside.
